Transform: AWS::Serverless-2016-10-31

Globals:

Description: Serverless backend for Genshin App.

Resources:
  # RDS

  # Cognito

  # Lambda Template
  LambdaName:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FunctionName
      PackageType: Image
      ImageConfig:
        Command:
          - ImageCommand
      Description: Function Description
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: API path
            Method: HTTP Method
            RequestParameters:
              - Path or Query parameter
      Policies: IAM policy
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: Latest

  # Sample lambdas
  sample:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
      PackageType: Image
      ImageConfig:
        Command:
          -
      Description:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /client
            Method: post
      Policies: ###
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: 
      DockerTag: 
